<?php

$outputtext .= '
	<h1>Terms Of Use</h1>
	<p>GN Capital Partners LLC, doing business as Gottanom, herein referred to as "Gottanom", "our", "we", or "us", operates the Gottanom.com website ("website").  Please read the following Terms of Use carefully before using the website. </p>
	<p>Terms Of Use</p>
	<p>By viewing, using, accessing, browsing, or submitting any content or material in connection with Gottanom.com website, you agree to these Terms of Use as a binding legal agreement between the you and Gottanom, without limitation or qualification. The Terms of Use (at <a href="http://www.gottanom.com/termsofuse.php">http://www.gottanom.com/termsofuse.php</a>) and Privacy Policy (at <a href="http://www.gottanom.com/privacyagreement.php">http://www.gottanom.com/privacyagreement.php</a>) are hereby incorporated in these Terms of Use by reference. The term "you" or "Operator" shall refer to any person or entity who views, uses, accesses, browses or submits any content or material in connection with the Gottanom.com website including, but not limited to, any delivery Operator or messenger employed directly by a restaurant or as an independent contractor on behalf of any restaurant for the purpose of delivering any food or drink orders.</p>
	<p>If you do not agree to the Gottanom Terms of Use, then you may not use the Gottanom.com website. We reserve the right to modify these Terms of Use at any time without prior notice. You agree that each view, use, access, browse or content submission shall be subject to the then-current Terms of Use (including the Gottanom Terms of use and Privacy Policy), and continued use of the Gottanom.com website now or following modifications in these Terms of Use confirms that you have read, accepted, and agreed to be bound by such modifications.</p>
	<p>For the purpose of this Terms of Use, "Diner" shall include any person or entity (including any other individuals located at the order delivery address) to whom an Operator delivers or attempts to deliver an order in connection with the Gottanom.com website.</p>
	<p>GOTTANOM DOES NOT PROVIDE TRANSPORTATION SERVICES, AND GOTTANOM IS NOT A TRANSPORTATION CARRIER. IT IS UP TO THE OPERATOR TO PROVIDE TRANSPORTATION SERVICES. GOTTANOM OFFERS SERVICES WHICH MAY INCLUDE INFORMATION REGARDING TRANSPORTATION SERVICES, BUT DOES NOT AND DOES NOT INTEND TO PROVIDE TRANSPORTATION SERVICES OR ACT IN ANY WAY AS A TRANSPORTATION CARRIER, AND HAS NO RESPONSIBILITY OR LIABILITY FOR ANY TRANSPORTATION SERVICES PROVIDED TO YOU BY SUCH THIRD PARTIES.</p>
	<p>Operator agrees to use any information collected in connection with the Gottanom.com website only for authorized purposes directly related to Operator&apos;s order delivery services. Operator agrees not to share or disclose any information collected in connection with the Gottanom.com website to third parties other than Gottanom or authorized restaurant personnel. Nothing in this paragraph shall prohibit Operator from disclosing a Diner&apos;s order information to the Diner placing such order.</p>
	<p>Gottanom allows users to select a charity of their choice for 1% of their order to be donated.  The 1% is limited to match each dollar up to a maximum of $50 for each order (e.g if an order is $10, we will donate $0.10 but if an order is $55, we will donate the maximum of $0.50).  The charity must be registered with Gottanom as a local partner.  Unless the charity has a formal contract with Gottanom, they will not be available to be selected.  Gottanom is willing to partner with any tax-exempt organization.</p>
	<p>Release of Liability </p>
	<p>Operator releases Gottanom from all liability for information acquired (or not acquired) by Operator or Diners through the website. Gottanom makes no representations concerning any information acquired by or accessed through the website. Operator releases Gottanom from all liability relating to Operator&apos;s use of the website and Diners&apos; access to and use of information acquired through the website. Operator understands that Gottanom does not, in any way, screen Diners. Gottanom makes no representations or warranties as to the conduct of Diners or Diner&apos;s use of information acquired through the website, including, but not limited to, Operator&apos;s delivery time, route and location. In no event shall Gottanom be liable for any damages whatsoever, whether direct, indirect, general, special, compensatory, consequential, exemplary and/or incidental, arising out of or relating to the conduct of Operator, Diners or anyone else&apos;s use of the website or information acquired through the website, including, without limitation, bodily injury, emotional distress, and any damages resulting in any way from communications or encounters arising from Operator&apos;s use of the website or any third-party&apos;s use of information acquired through the website. As such, Operator agrees to take reasonable precautions and exercise the utmost personal care in all interactions with any person Operator encounters in connection with Operator&apos;s use of the website.</p>
	<p>Copyright &copy; 2014 GN Capital Partners LLC All Rights Reserved.</p>
	';

?>